baseurl = "/"
languageCode = "en-us"
title = "JM"
theme = "hugo-lithium"
googleAnalytics = "UA-121816467-2"
disqusShortname = "jmcanovas"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "Contact"
    url = "/contact/"
[[menu.main]]
    name = "Cross Validated"
    url = "https://stats.stackexchange.com/users/218995/juan-manuel"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/canovasjm"
[[menu.main]]
    name = "Portfolio"
    url = "/portfolio/"
[[menu.main]]
    name = "Posts"
    url = "https://canovasjm.netlify.com"
[[menu.main]]
    name = "Shiny Apps"
    url = "/shiny_apps/"


[params]
    description = "My blog"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    #[params.logo]
    #url = "logo.png"
    #width = 50
    #height = 50
    #alt = "Logo"


